# Generated by Django 3.0.8 on 2020-07-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('population', models.IntegerField(blank=True, null=True)),
                ('growth_rate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'county',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'land',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LandImprovement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('management', models.TextField()),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('improvement', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'land_improvement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status', models.TextField()),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'owner',
                'managed': False,
            },
        ),
    ]
