# Generated by Django 3.0.8 on 2020-07-23 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('population', models.IntegerField()),
                ('growth_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LandImprovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management', models.CharField(max_length=250)),
                ('cost', models.IntegerField()),
                ('improvement', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('area', models.CharField(max_length=250)),
                ('county_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_main.County')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_main.Owner')),
            ],
        ),
    ]
