# Generated by Django 3.0.8 on 2020-07-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='land',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='landimprovement',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='county',
            name='growth_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='county',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='county',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='area',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landimprovement',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landimprovement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='landimprovement',
            name='improvement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landimprovement',
            name='management',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='owner',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='owner',
            name='status',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='county',
            table='County',
        ),
        migrations.AlterModelTable(
            name='land',
            table='Land',
        ),
        migrations.AlterModelTable(
            name='landimprovement',
            table='LandImprovement',
        ),
        migrations.AlterModelTable(
            name='owner',
            table='Owner',
        ),
    ]
