# Generated by Django 3.0.8 on 2020-07-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_main', '0002_djangomigrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandDetails',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('rating', models.SmallIntegerField()),
                ('area', models.IntegerField()),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_status', models.CharField(max_length=50)),
                ('county_name', models.CharField(max_length=50)),
                ('county_pop', models.IntegerField()),
                ('county_growth_rate', models.FloatField()),
            ],
            options={
                'db_table': 'vLandDetails',
                'managed': False,
            },
        ),
    ]
